platform :ios,’8.0’
use_frameworks!
target ‘CJXBiOSdemo’ do
pod 'AFNetworking', '~> 3.1.0’
pod 'MBProgressHUD', '~> 0.9.1’
pod 'MJRefresh', '~> 2.4.12’
pod 'SDWebImage', '~> 3.7.3’
pod 'SDCycleScrollView', '~> 1.3’

pod 'MJExtension', '~> 2.5.10'
pod 'JSBadgeView', '~> 1.4.1'
pod 'IMYWebView', '~> 0.8'

end